name: Release JAR

on:
  push:
    tags:
      - 'v*' # Triggers on tags starting with 'v'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: 'maven'

      - name: Build with Maven
        run: |
          mvn -B clean package -DskipTests --file pom.xml
          chmod +x target/*.jar

      - name: Get tag version
        id: get-version
        run: |
          echo "version=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Create Release
        id: create-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ steps.get-version.outputs.version }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: target/*.jar
